# Generated by Django 5.0.2 on 2025-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=100)),
                ('setor_solicitante', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('local_servico', models.CharField(max_length=200)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_servico', models.CharField(choices=[('eletrico', 'Elétrico'), ('hidraulico', 'Hidráulico'), ('refrigeracao', 'Refrigeração'), ('pintura', 'Pintura'), ('outro', 'Outro')], max_length=20)),
                ('tipo_manutencao', models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('melhoria', 'Melhoria')], max_length=20)),
                ('outro_tipo_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_problema', models.TextField()),
            ],
        ),
    ]
